export const AUTHORITIES = {
  VIEW_DASHBORD_ADMIN: 'VIEW_DASHBORD_ADMIN',
  VIEW_DASHBORD_OTHER: 'VIEW_DASHBORD_OTHER',
  VIEW_CARDS_ADMIN: 'VIEW_CARDS_ADMIN',
  VIEW_MONTANT_ENCAISSE: 'VIEW_MONTANT_ENCAISSE',
  VIEW_FINANCE_CHART: 'VIEW_FINANCE_CHART',
  READ_ADMINISTRATEUR: 'READ_ADMINISTRATEUR',

  READ_USER_LIST: 'READ_USER_LIST',
  READ_USER_SYSTEM: 'READ_USER_SYSTEM',
  READ_RETAIL_LIST: 'READ_RETAIL_LIST',
  READ_RETAIL_LIST__AREA: 'READ_RETAIL_LIST__AREA',
  ADD_USER: 'ADD_USER',
  UPDATE_PROFILE_REVENDEUR: 'UPDATE_PROFILE_REVENDEUR',

  READ_RETAIL_SUMMARY_LIST_ALL: 'READ_RETAIL_SUMMARY_LIST_ALL',
  READ_RETAIL_SUMMARY_LIST_AREA: 'READ_RETAIL_SUMMARY_LIST_AREA',

  WRITE_ROLE: 'WRITE_ROLE',

  READ_CATEGORY: 'READ_CATEGORY',
  READ_PRODUCT: 'READ_PRODUCT',
  ANTIVIRUS_KEY_MANAGEMENT: 'ANTIVIRUS_KEY_MANAGEMENT',

  ADD_SUBSCRIPTION_REQUEST: 'ADD_SUBSCRIPTION_REQUEST',
  ADD_SUBSCRIPTION_REQUEST_ALL: 'ADD_SUBSCRIPTION_REQUEST_ALL',
  SEARCH_SUBSCRIPTION_REQUEST_ALL: 'SEARCH_SUBSCRIPTION_REQUEST_ALL',
  SEARCH_SUBSCRIPTION_REQUEST_RETAIL: 'SEARCH_SUBSCRIPTION_REQUEST_RETAIL',
  READ_SUBSCRIPTION_REQUEST_ALL: 'READ_SUBSCRIPTION_REQUEST_ALL',
  READ_SUBSCRIPTION_REQUEST_RETAIL: 'READ_SUBSCRIPTION_REQUEST_RETAIL',
  READ_SUBSCRIPTION_REQUEST_AREA: 'READ_SUBSCRIPTION_REQUEST_AREA',

  READ_REQUEST_MIGRATION: 'READ_REQUEST_MIGRATION',
  READ_REQUEST_CHDEBIT: 'READ_REQUEST_CHDEBIT',
  READ_REQUEST_TRANSFERT: 'READ_REQUEST_TRANSFERT',

  READ_COMMANDE: 'READ_COMMANDE',
  READ_PARINAGE: 'READ_PARINAGE',
  READ_CONFIG_NOTIFICATION: 'READ_CONFIG_NOTIFICATION',

  CREATE_INVOICE_AVOIR: 'CREATE_INVOICE_AVOIR',
  READ_INVOICE_AVOIR: 'READ_INVOICE_AVOIR',
  READ_BLUR_INVOICE_AVOIR: 'READ_BLUR_INVOICE_AVOIR',

  READ_BORDEREAU: 'READ_BORDEREAU',
  READ_BORDEREAU_RETAIL: 'READ_BORDEREAU_RETAIL',

  READ_RECLAMATION: 'READ_RECLAMATION',
  ADD_RECLAMATION: 'ADD_RECLAMATION',

  VIEW_HISTORIQUE: 'VIEW_HISTORIQUE',

  READ_COMMISSION: 'READ_COMMISSION',
  UPDATE_SUBSCRIPTION_REQUEST_STATUS: 'UPDATE_SUBSCRIPTION_REQUEST_STATUS',
  CLIENT_EXTRAIR_LIST: 'CLIENT_EXTRAIR_LIST',
}

export const PAGE_SIZES = [10, 20, 50, 100]

export const STATUS_COLORS = {
  'Actif': '#28a745',
  'Résilié': '#dc3545',
  'En cours': '#ffc107',
  'Traité': '#17a2b8',
  'Validé': '#28a745',
  'Refusé': '#dc3545',
  'En attente': '#6c757d',
  'Nouveau': '#007bff',
}

export const BRAND_COLOR = '#590E9C'
