spring.application.name=spring-boot-metrics
management.metrics.tags.application=${spring.application.name}
management.endpoints.web.exposure.include=prometheus
management.endpoint.prometheus.enabled=true

Statut.chifco.etude=etude
Statut.chifco.annulee = Annulee
Statut.chifco.ConfirmationClient = Confirmation Client
Statut.chifco.Construction = Construction Ligne 
Statut.chifco.Reservation = Reservation 
Statut.chifco.Tirage.Jarretiere = Tirage Jarretiere  
Statut.chifco.Miseenservice = Mise en service
Statut.chifco.Cloturee = statuTT Cloture

crm.app.jwtSecret = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9eyJhbGciOiJIUzI1NiIsIn
crm.app.jwtExpirationMs = 580000

server.port = 8282
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

tva=7.0
timbrefiscale=1
avanceFacture5g=2
prixracordement=40.0
prixhtRacordment = 33.614
tvaracordement=0.0


calcule.TT.raccordement=26.823
clacule.TT.Service.8mo=21.76
clacule.TT.Service.10mo=21.76
clacule.TT.Service.12mo=22.411
clacule.TT.Service.20mo=23.469
clacule.TT.Service.30mo=31.096
clacule.TT.Service.50mo=32.458
#File upload/download
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.error.path=/error
# Ehcache Configuration
spring.cache.ehcache.config=classpath:ehcache.xml

server.servlet.session.timeout=1440m
server.servlet.session.tracking-modes=cookie
server.servlet.session.cookie.http-only=false
server.servlet.session.cookie.secure=false

security.enable-csrf= false
delaiDePaiement = 10
firstFactureGracePeriod  = 3
#apres 4 jour => reste 6 jours de l'echance
rappelleJour1=6

#apres 8 jour => reste 2 jours de l'echance
rappelleJour2 = 2

#15 jour de creation => 5 jours aprtire de l'echance
reactivationservices = 5
net.sf.jasperreports.awt.ignore.missing.font=true
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
spring.mvc.async.request-timeout=2m

facture.resilation.modem=126
prime.commission.aquisition.demande.plus100.ms=800
commission.acquisition.demande.centplus10Mo = 7
commission.acquisition.demande.centplus20Mo = 7
commission.acquisition.demande.centplus30Mo = 7
commission.acquisition.demande.centplus50Mo = 7
commission.acquisition.demande.centplus100Mo = 7
commission.acquisition.demande.deuxCentplus10Mo = 9
commission.acquisition.demande.deuxCentplus20Mo = 9
commission.acquisition.demande.deuxCentplus30Mo = 9
commission.acquisition.demande.deuxCentplus50Mo = 9
commission.acquisition.demande.deuxCentplus100Mo = 9

commission.acquisition.demande.troisCentplus10Mo = 11
commission.acquisition.demande.troisCentplus20Mo = 11
commission.acquisition.demande.troisCentplus30Mo = 11
commission.acquisition.demande.troisCentplus50Mo = 11
commission.acquisition.demande.troisCentplus100Mo = 11

commision.acquisition.demande.0.49.10Mo = 0
commision.acquisition.demande.50.99.10Mo = 0

commision.acquisition.demande.0.49.20Mo = 0
commision.acquisition.demande.50.99.20Mo = 0

commision.acquisition.demande.0.49.30Mo = 0
commision.acquisition.demande.50.99.30Mo = 0

commision.acquisition.demande.0.49.50Mo = 0
commision.acquisition.demande.50.99.50Mo = 0

commision.acquisition.demande.0.49.100Mo = 0
commision.acquisition.demande.50.99.100Mo = 0


commission.acquisition.activation.12Mo.0.49.echance = 40
commission.acquisition.activation.12Mo.0.49.hechance = 37
commission.acquisition.activation.12Mo.50.99.echance = 43
commission.acquisition.activation.12Mo.50.99.hechance = 40


commission.acquisition.activation.12Mo.100.echance = 40
commission.acquisition.activation.12Mo.100.hechance = 37
commission.acquisition.activation.12Mo.200.echance = 43
commission.acquisition.activation.12Mo.200.hechance = 40
commission.acquisition.activation.12Mo.300.echance = 43
commission.acquisition.activation.12Mo.300.hechance = 40


commission.acquisition.activation.20Mo.0.49.echance = 42
commission.acquisition.activation.20Mo.0.49.hechance = 39
commission.acquisition.activation.20Mo.50.99.echance = 45
commission.acquisition.activation.20Mo.50.99.hechance = 42

commission.acquisition.activation.20Mo.100.echance = 42
commission.acquisition.activation.20Mo.100.hechance = 39
commission.acquisition.activation.20Mo.200.echance = 45
commission.acquisition.activation.20Mo.200.hechance = 42
commission.acquisition.activation.20Mo.300.echance = 45
commission.acquisition.activation.20Mo.300.hechance = 42


commission.acquisition.activation.30Mo.0.49.echance = 44
commission.acquisition.activation.30Mo.0.49.hechance = 41
commission.acquisition.activation.30Mo.50.99.echance = 47
commission.acquisition.activation.30Mo.50.99.hechance = 44

commission.acquisition.activation.30Mo.100.echance = 44
commission.acquisition.activation.30Mo.100.hechance = 41

commission.acquisition.activation.30Mo.200.echance = 47
commission.acquisition.activation.30Mo.200.hechance = 44
commission.acquisition.activation.30Mo.300.echance = 47
commission.acquisition.activation.30Mo.300.hechance = 44


commission.acquisition.activation.50Mo.0.49.echance = 52
commission.acquisition.activation.50Mo.0.49.hechance = 48
commission.acquisition.activation.50Mo.50.99.echance = 55
commission.acquisition.activation.50Mo.50.99.hechance =51

commission.acquisition.activation.50Mo.100.echance = 52
commission.acquisition.activation.50Mo.100.hechance = 48
commission.acquisition.activation.50Mo.200.echance = 55
commission.acquisition.activation.50Mo.200.hechance =51
commission.acquisition.activation.50Mo.300.echance = 55
commission.acquisition.activation.50Mo.300.hechance = 51




commission.acquisition.activation.100Mo.0.49.echance = 62
commission.acquisition.activation.100Mo.0.49.hechance = 58
commission.acquisition.activation.100Mo.50.99.echance = 65
commission.acquisition.activation.100Mo.50.99.hechance = 61

commission.acquisition.activation.100Mo.100.echance = 62
commission.acquisition.activation.100Mo.100.hechance = 58

commission.acquisition.activation.100Mo.200.echance = 65
commission.acquisition.activation.100Mo.200.hechance = 61
commission.acquisition.activation.100Mo.300.echance = 65
commission.acquisition.activation.100Mo.300.hechance = 61



commission.paiement.echance12Mo.pourcent = 5
commission.paiement.hechance12Mo.pourcent = 4

commission.paiement.echance20Mo.pourcent = 5
commission.paiement.hechance20Mo.pourcent = 4

commission.paiement.echance30Mo.pourcent = 5
commission.paiement.hechance30Mo.pourcent = 4

commission.paiement.echance50Mo.pourcent = 5
commission.paiement.hechance50Mo.pourcent = 4

commission.paiement.echance100Mo.pourcent = 5
commission.paiement.hechance100Mo.pourcent = 4


facture.resilation.prix.depasse.6 = 33.529
facture.resilation.prix.non.depasse.6 = 41.933
facture.resilation.date.fin = 15

promo.commision.palier.one.min = 1
promo.commision.palier.one.max = 20

promo.commision.palier.two.min = 21
promo.commision.palier.two.max = 30

promo.commision.palier.three.min = 31
promo.commision.palier.three.max = 50

promo.commision.palier.four.min = 50
promo.commision.palier.four.max = 99

promo.commision.palier.five.min = 100

server.max-http-request-header-size=85536
grantTypeRunPay = runpay_terminal
grantTypeMazam = mazam_terminal
grantTypeEnda = enda_terminal
grantTypeClient=chatbot_terminal
commision.acquisition.avance.echance = 40

commision.acquisition.avance.hors.echance = 37




echanceOffrePromo = 2025-01-01

