app.datasource.crm.url=jdbc:sqlserver://localhost;databaseName=CRM_CHIFCO4;
app.datasource.crm.username=sa
app.datasource.crm.password=Chifc@2022
app.datasource.crm.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

app.datasource.internet.url=jdbc:mariadb://172.16.16.229:3306/radius
app.datasource.internet.username=crm
app.datasource.internet.password=crm2022
app.datasource.internet.driverClassName=org.mariadb.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
serverNameCRM=Server 1

spring.mail.host=smtp-fr.securemail.pro
#spring.mail.port= 465
spring.mail.port= 587 
spring.mail.username=oussama.hassani@chifco.com
spring.mail.password=Oussam@2021*
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

pathBordereau=/media/Bordereau/
pathCommission=/media/commission/
pathPhoto= /media/photos/
pathFacture= /media/facture/
pathDemandesAbonnement= /media/abonnement/cin/
pathuploadxlsx= /media/abonnement/excel/
pathModemxlsx= /media/modem/excel/
pathFicheStock= /media/fichestock
pathRecu=/media/paiementrecu/
pathRecuResilation=/media/resiliationrecu/
pathAvoir=/media/avoirClient/
pathParinage=/media/parinage/
#apres 8 jour => reste 2 jours de l'echance
rappelleJour2 = 2
webSiteNety = https://preprod.nety.tn
#15 jour de creation => 5 jours aprtire de l'echance
#reactivationservices = 5

cron.payment.disconnection.remind.before=true
cron.payment.disconnection.remind=true
cron.payment.disconnection.remind.after=true
cron.invoice.generation=true
cron.TTservice.racordement=true
cron.TTservice.service=true
net.sf.jasperreports.awt.ignore.missing.font=true
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
returnAdresse=http://localhost:8282
recaptcha.sitekey=6LeJlmwnAAAAANqZz6--ntCDGsu2U--3hL_JtPmh
recaptcha.secretkey=6LeJlmwnAAAAAAoohnXTAQR-bZjjGL8hm6J7QEgx
#logging.level.root=OFF


blocage.mail.revendeur.responsable.finance=oussama.hassani@chifco.com
blocage.mail.revendeur.responsable.nety = rym.arfaoui@chifco.com
xls.mail.responsable = rym.arfaoui@chifco.com
xls.mail.responsable.cc = rym.arfaoui@chifco.com
promo.commision.palier.one.min = 1
promo.commision.palier.one.max = 20

promo.commision.palier.two.min = 21
promo.commision.palier.two.max = 30

promo.commision.palier.three.min = 31
promo.commision.palier.three.max = 50

promo.commision.palier.four.min = 50
promo.commision.palier.four.max = 99

promo.commision.palier.five.min = 100
clientSecretRunPay = e477ecce5d4454228833b3d12eb8ebe5d0389162856631b401eb4293405f2686
clientSecretEnda = e444ecce5d4454228833b3d12eb8ebe5d3339162856631b401eb4293405f4444

konnectKey = 661e5ef858953ef7de898bc7:YZJqZGBH6xou44omNHS
waltId =661e5ef858953ef7de898bcb
urlKonnect = https://api.preprod.konnect.network/api/v2/
PaymeeUrl = https://sandbox.paymee.tn/api/v2/payments/
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expirationMs=518400000
# 14 day for refresh token
jwt.refreshExpirationMs=1209600000 
