
app.datasource.crm.url=jdbc:sqlserver://172.16.16.138;databaseName=chif2026;
app.datasource.crm.username=sa
app.datasource.crm.password=Chifc000
app.datasource.crm.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
app.datasource.internet.url=jdbc:mariadb://172.16.16.229:3306/radius
app.datasource.internet.username=crm
app.datasource.internet.password=crm2022
#app.datasource.internet.url=jdbc:mariadb://197.31.8.198:3306/radius
#app.datasource.internet.username=crmchifco
#app.datasource.internet.password=Hng434PG+Ubr3

app.datasource.internet.driverClassName=org.mariadb.jdbc.Driver
crm.app.jwtExpirationMs = 150000
#crm.app.jwtSecret = crmchifco
#app.datasource.internet.url=jdbc:mariadb://197.31.8.196:3306/radius
#app.datasource.internet.username=crmchifco
#app.datasource.internet.password=Hng434PG+Ubr3
#app.datasource.internet.driverClassName=org.mariadb.jdbc.Driver


spring.jpa.show-sql=false

serverNameCRM=Server 1

spring.mail.host=smtp-fr.securemail.pro
#spring.mail.port= 465
spring.mail.port= 587 
spring.mail.username=oussama.hassani@chifco.com
spring.mail.password=Oussam@2021*
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

pathBordereau=/mediaCrm/Bordereau/
pathPhoto= /mediaCrm/photos/
pathCommission=/mediaCrm/commission/
pathFacture= /mediaCrm/facture/
pathDemandesAbonnement= /mediaCrm/abonnement/cin/
pathuploadxlsx= /mediaCrm/abonnement/excel/
pathModemxlsx= /mediaCrm/modem/excel/
pathFicheStock= /mediaCrm/fichestock
pathRecu=/mediaCrm/paiementrecu/
pathAvoir=/mediaCrm/avoirClient/
pathParinage=/mediaCrm/parinage/
pathPgh=/PGH/Chifco/

pathReclamation=/mediaCrm/reclamation/

pathRecuResilation=/mediaCrm/resiliationrecu/


#apres 8 jour => reste 2 jours de l'echance
rappelleJour2 = 2

#15 jour de creation => 5 jours aprtire de l'echance
reactivationservices = 5

cron.payment.disconnection.remind.before=false
cron.payment.disconnection.remind=false
cron.payment.disconnection.remind.after=false
cron.invoice.generation=false
cron.TTservice.racordement=false
cron.TTservice.service=false
net.sf.jasperreports.awt.ignore.missing.font=true
returnAdresse=https://crm.chifco.com
recaptcha.sitekey=6LeJlmwnAAAAANqZz6--ntCDGsu2U--3hL_JtPmh
recaptcha.secretkey=6LeJlmwnAAAAAAoohnXTAQR-bZjjGL8hm6J7QEgx
#konnectKey =661e5ef858953ef7de898bc7:Lvf3yuUNsvkGuLuxpOstsSOI0J4VdvT
#konnectKey = 661e5e4ce0565de509f8b6b7:x0wgljVRULBIJkd5jAm2xXkCQDg
#urlKonnect = https://api.konnect.network/api/v2/
#waltId =  661e5e4ce0565de509f8b6bb
konnectKeyOld =661e5ef858953ef7de898bc7:YZJqZGBH6xou44omNHS
konnectKeyppd=68daad4c2c610a17465cb4d0:sgiWAxiLEOOAclgkgruiJRSLh0XZjcfm
konnectKey=661e5e4ce0565de509f8b6b7:LrZRLiXrnLdavbWL9oa
click.to.pay.loginold =0338206519
click.to.pay.passwordold =9upgV4FJF
click.to.pay.login =0338206519
click.to.pay.password =Zba5k4DP7
urlclick=https://ipay.clictopay.com
waltId =661e5e4ce0565de509f8b6bb
waltIdold =68daad4f2c610a17465cb517
urlKonnectold = https://api.preprod.konnect.network/api/v2/
urlKonnect = https://api.konnect.network/api/v2/

PaymeeUrl = https://sandbox.paymee.tn/api/v2/payments/
webSiteNety = https://preprod.nety.tn

blocage.mail.revendeur.responsable.finance=oussama.hassani@chifco.com
blocage.mail.revendeur.responsable.nety = rym.arfaoui@chifco.com
xls.mail.responsable = rym.arfaoui@chifco.com
access.mail.modem.XDSL.nety = oussama.hassani@chifco.com
xls.mail.responsable.cc =  rym.arfaoui@chifco.com
xls.mail.sav = rym.arfaoui@chifco.com
clientSecretRunPay = e477ecce5d4454228833b3d12eb8ebe5d0389162856631b401eb4293405f2686
clientSecretEnda = e444ecce5d4454228833b3d12eb8ebe5d3339162856631b401eb4293405f4444
clientSecretkey=f93a4b3c2e8df49f15c7199fa1b54b90e1a3fdd2ce8a7e2f4c97108a0f56dc32

clientSecretMazam =e477ecce5d4454228833b3d12eb8ebe5d0389162856631b401eb4293405f2699



#Mobile app secret,token expiration and refresh token expiration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#1 h :3600000 ,518400000:6days
jwt.expirationMs=518400000
# 14 day for refresh token
jwt.refreshExpirationMs=1209600000 

#credentials for token nety tv
jwt.secretnetytv=6A5D4F3E2C1B0A9F8E7D6C5B4A39281736251403827160594837261503847261
#for only one day
jwt.expirationMsnetytv=86400000 
# 14 day for refresh token
jwt.refreshExpirationMsnetytv=1209600000 

